services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
      image: docker.elastic.co/kibana/kibana:8.17.0
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
