services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
